"""enable btree_gist extension

Split out from the schema migration on purpose: autogenerate diffs
SQLAlchemy metadata against the reflected DB, so it can never emit a
CREATE EXTENSION for the operator classes ex_agendamentos_no_overlap needs
(gist can't index a plain uuid for equality on its own — btree_gist adds
that). This has to run and commit before the exclusion constraint's DDL, so
it stays its own revision rather than folded into the autogenerated one.

Revision ID: 0001
Revises:
Create Date: 2026-08-21

"""
from typing import Sequence, Union

from alembic import op

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")


def downgrade() -> None:
    # Left installed on downgrade — other things may depend on it by then,
    # and dropping an extension is not the business of this revision.
    pass
